+================================================
+                                                
+  Centroid  -  Vectric machine output configuration file   
+  http://www.centroidcnc.com/  
+                                                
+================================================
+                                                
+ History                                        
+                                                
+ Who      When       What                         
+ ======== ========== ===========================
+ Brian    11/01/2007 Written
+ Olivier  19/01/2007 compensate tool height, header, toolchange, footer
+ Olivier  19/01/2007 inches
+================================================

POST_NAME = "Centroid (inch) (*.cnc)"

FILE_EXTENSION = "cnc"

UNITS = "INCHES"

+------------------------------------------------
+    Line terminating characters                 
+------------------------------------------------

LINE_ENDING = "[13][10]"

+------------------------------------------------
+    Block numbering                             
+------------------------------------------------

LINE_NUMBER_START = 10
LINE_NUMBER_INCREMENT = 10
LINE_NUMBER_MAXIMUM = 999999

+================================================
+                                                
+    Formating for variables                     
+                                                
+================================================

VAR LINE_NUMBER = [N|A|N|04.0]
VAR SPINDLE_SPEED = [S|A| S|1.0]
VAR FEED_RATE = [F|C| F|1.0]
VAR X_POSITION = [X|C| X|1.4]
VAR Y_POSITION = [Y|C| Y|1.4]
VAR Z_POSITION = [Z|C| Z|1.4]
VAR X_HOME_POSITION = [XH|A| X|1.4]
VAR Y_HOME_POSITION = [YH|A| Y|1.4]
VAR Z_HOME_POSITION = [ZH|A| Z|1.4]
VAR ARC_CENTRE_I_INC_POSITION = [I|A| I|1.4]
VAR ARC_CENTRE_J_INC_POSITION = [J|A| J|1.4]


+================================================
+                                                
+    Block definitions for toolpath output       
+                                                
+================================================

+---------------------------------------------------
+  Commands output at the start of the file
+---------------------------------------------------

begin HEADER

"[N] ; ---------------------------------------------"
"[N] ; Filename: [TOOLPATH_NAME]"
"[N] ; Generated by VCarve Pro 3.1 for Centroid CNC"
"[N] ; ---------------------------------------------"
"[N] ; Move to Z home - Tool Length Compensation Cancel"
"[N] M25 G49"
"[N] ; Circular Interpolation Plane Selection XY - Cutter Compensation Cancel"
"[N] G17 G40"
"[N] ; Select Inches Units"
"[N] G20"
"[N] ; Canned Cycle Cancel"
"[N] G80"
"[N] ; Absolute Positioning Mode"
"[N] G90"
"[N] ; Initial Point Return"
"[N] G98"

"[N] ; ---------------------------------------------"
"[N] ; Toolchange: T[T] - Speed:[S]"
"[N] ; ---------------------------------------------"
"[N] ; Tool Length Compensation Cancel - Move to Z home"
"[N] G49 H0 M25"
"[N] ; Absolute Positioning Mode - Rapid Positioning"
"[N] G90 G0[XH][YH]"
"[N] ; Start Tool Change"
"[N] T[T] M6"
"[N] ; Spindle on CW"
"[N] M3 [S][F]"
"[N] ; Pause for 2 seconds"
"[N] G4 P2"
"[N] ; Tool Length Compensation (+)"
"[N] G43 G0[ZH] H[T]"
"[N] ; ---------------------------------------------"

+---------------------------------------------------
+  Commands output for rapid moves 
+---------------------------------------------------

begin RAPID_MOVE

"[N] G0[X][Y][Z]"

+---------------------------------------------------
+  Commands output for feed rate moves
+---------------------------------------------------

begin FEED_MOVE

"[N] G1[X][Y][Z][F]"

+---------------------------------------------------
+  Commands output for the first clockwise arc move
+---------------------------------------------------

begin FIRST_CW_ARC_MOVE

"[N] G2[X][Y][I][J][F]"

+---------------------------------------------------
+  Commands output for clockwise arc  move
+---------------------------------------------------

begin CW_ARC_MOVE

"[N] G2[X][Y][I][J]"

+---------------------------------------------------
+  Commands output for the first counterclockwise arc move
+---------------------------------------------------

begin FIRST_CCW_ARC_MOVE

"[N] G3[X][Y][I][J][F]"

+---------------------------------------------------
+  Commands output for counterclockwise arc  move
+---------------------------------------------------

begin CCW_ARC_MOVE

"[N] G3[X][Y][I][J]"

+---------------------------------------------------
+  Commands output at toolchange
+---------------------------------------------------

begin TOOLCHANGE

"[N] ; ---------------------------------------------"
"[N] ; Toolchange: T[T] - Speed:[S]"
"[N] ; ---------------------------------------------"
"[N] ; Tool Length Compensation Cancel - Move to Z home"
"[N] G49 H0 M25"
"[N] ; Absolute Positioning Mode - Rapid Positioning"
"[N] G90 G0[XH][YH]"
"[N] ; Start Tool Change"
"[N] T[T] M6"
"[N] ; Spindle on CW"
"[N] M3 [S][F]"
"[N] ; Pause for 2 seconds"
"[N] G4 P2"
"[N] ; Tool Length Compensation (+)"
"[N] G43 G0[ZH] H[T]"
"[N] ; ---------------------------------------------"

+---------------------------------------------------
+  Commands output at the end of the file
+---------------------------------------------------

begin FOOTER

"[N] ; ---------------------------------------------"
"[N] ; Tool Length Compensation Cancel - Move to Z home"
"[N] G49 H0 M25"
"[N] ; Spindle off"
"[N] M5"
"[N] ; Coolant Off"
"[N] M9"
"[N] ; Canned Cycle Cancel"
"[N] G80"
"[N] ; End-Custom M Code"
"[N] M30"
